Roomie/Models/Appartment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roomie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appartment()
        {
            this.AppartmentOwners = new HashSet<AppartmentOwner>();
            this.ProfileLinkers = new HashSet<ProfileLinker>();
        }
    
        public decimal RentCost { get; set; }
        public string Description { get; set; }
        public Nullable<int> PhotoID { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> ZipCode { get; set; }
        public string State { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppartmentOwner> AppartmentOwners { get; set; }
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileLinker> ProfileLinkers { get; set; }
    }
}

Roomie/Models/AppartmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Roomie.Models
{
    public class AppartmentViewModel
    {
        public int ID { get; set; }
        public decimal RentCost { get; set; }
        public string Description { get; set; }
        public Nullable<int> PhotoID { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }

        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileLinker> ProfileLinkers { get; set; }
    }
}

Roomie/Controllers/AppartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Roomie.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace Roomie.Controllers
{
    [Authorize]
    public class AppartmentsController : Controller
    {
        private RoomieEntities db = new RoomieEntities();


        // GET: Appartments
        public async Task<ActionResult> MyAppartments()
        {
            var userId = User.Identity.GetUserId();
            var appartmentOwner = db.AppartmentOwners.Find(userId);
            var appartments = appartmentOwner.Appartment;
            return View(appartments);
        }
        public async Task<ActionResult> BookAppointment(int id)
        {
            Appartment appartment = await db.Appartments.FindAsync(id);
            return View(appartment);
        }

        // GET: Appartments
        public async Task<ActionResult> Index()
        {
            var appartments = db.Appartments.Include(a => a.Photo);
            return View(await appartments.ToListAsync());
        }

        // GET: Appartments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartment appartment = await db.Appartments.FindAsync(id);
            if (appartment == null)
            {
                return HttpNotFound();
            }
            return View(appartment);
        }

        [Authorize(Roles ="Owner")]
        // GET: Appartments/Create
        public ActionResult Create()
        {
            ViewBag.PhotoID = new SelectList(db.Photos, "ID", "ImageLocation");
            return View();
        }

        // POST: Appartments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "RentCost,Description,PhotoID,Street,City,Country,ZipCode,State")] Appartment appartment, HttpPostedFileBase photoInput)
        {
            bool isValid = ModelState.IsValid;
            if(isValid && photoInput!=null && photoInput.ContentLength>0 )
            {
                if(!photoInput.ContentType.StartsWith("image/"))
                {
                    isValid = false;
                    ModelState.AddModelError("PhotoID", "Photo much be an image");
                }
                
            }

            if (isValid)
            {

                if (photoInput != null && photoInput.ContentLength > 0)
                {
                    var imageFolder = Server.MapPath("/UploadedImages");
                    var imageFileName = DateTime.Now.ToString("yyyy-MM-dd_HHmmss_fff") + "_" + photoInput.FileName;
                    var imagePath = Path.Combine(imageFolder, imageFileName);

                    photoInput.SaveAs(imagePath);
                    var photo = new Photo()
                    {
                        ImageLocation = imageFileName

                    };

                    appartment.Photo = photo; 
                }
                var userId = User.Identity.GetUserId();
                var appartmentOwner = db.AppartmentOwners.Find(userId);
                appartmentOwner.Appartment = appartment;
                db.Entry(appartmentOwner).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PhotoID = new SelectList(db.Photos, "ID", "ImageLocation", appartment.PhotoID);
            return View(appartment);
        }

        // GET: Appartments/Edit/5
        public async Task<ActionResult> Edit()
        {
            var userId = User.Identity.GetUserId();
            var appartmentOwner = db.AppartmentOwners.Find(userId);
            var appartments = appartmentOwner.Appartment;
            return View(appartments);
        }

        // POST: Appartments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,RentCost,Description,PhotoID,Street,City,Country")] Appartment appartment, HttpPostedFileBase photoInput)
        {
            bool isValid = ModelState.IsValid;

            if (isValid && photoInput != null && photoInput.ContentLength > 0)
            {
                if (!photoInput.ContentType.StartsWith("image/"))
                {
                    isValid = false;
                    ModelState.AddModelError("PhotoID", "Photo much be an image");
                }

            }

            if (isValid)
            {

                if (photoInput != null && photoInput.ContentLength > 0)
                {
                    var imageFolder = Server.MapPath("/UploadedImages");
                    var imageFileName = DateTime.Now.ToString("yyyy-MM-dd_HHmmss_fff") + "_" + photoInput.FileName;
                    var imagePath = Path.Combine(imageFolder, imageFileName);

                    photoInput.SaveAs(imagePath);
                    var photo = new Photo()
                    {
                        ImageLocation = imageFileName

                    };

                    appartment.Photo = photo;
                }

                db.Entry(appartment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PhotoID = new SelectList(db.Photos, "ID", "ImageLocation", appartment.PhotoID);
            return View(appartment);
        }

        // GET: Appartments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartment appartment = await db.Appartments.FindAsync(id);
            if (appartment == null)
            {
                return HttpNotFound();
            }
            return View(appartment);
        }

        // POST: Appartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Appartment appartment = await db.Appartments.FindAsync(id);
            db.Appartments.Remove(appartment);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Roomie/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Roomie.Models;

namespace Roomie.Controllers
{
    public class PhotosController : Controller
    {
        private RoomieEntities db = new RoomieEntities();

        // GET: Photos
        public async Task<ActionResult> Index()
        {
            return View(await db.Photos.ToListAsync());
        }

        // GET: Photos/Details/5
        public  ActionResult Details(int? id, string cssClass)
        {
            Photo photo =  db.Photos.Find(id);
            ViewBag.cssClass = cssClass;
            return PartialView(photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ImageLocation,id")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Photos.Add(photo);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(photo);
        }

        // GET: Photos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = await db.Photos.FindAsync(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ImageLocation,id")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(photo);
        }

        // GET: Photos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = await db.Photos.FindAsync(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Photo photo = await db.Photos.FindAsync(id);
            db.Photos.Remove(photo);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Roomie/Views/Appartments/BookAppointment.cshtml
@model Roomie.Models.Appartment

@{
    ViewBag.Title = "BookAppointment";
}

<h2>Book Appointment</h2>

<div>
    

</div>

Roomie/Views/Appartments/Create.cshtml
@model Roomie.Models.Appartment

@{
    ViewBag.Title = "Create Apartment";
}

<h2>Apartment</h2>


@using (Html.BeginForm("Create","Appartments",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.RentCost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RentCost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RentCost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    

    <div class="form-group">
            @Html.LabelFor(model => model.PhotoID, "PhotoID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="photoInput" name="photoInput" placeholder="Upload File" />


                @*@Html.DropDownList("PhotoID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.PhotoID, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Roomie/Views/Appartments/Delete.cshtml
@model Roomie.Models.Appartment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appartment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RentCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo.ImageLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo.ImageLocation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Roomie/Views/Appartments/Details.cshtml
@model Roomie.Models.Appartment

@{
    ViewBag.Title = "Details";
    var key = System.Configuration.ConfigurationManager.AppSettings["mapskey"];
    var mapurlBase = "https://www.google.com/maps/embed/v1/place";
    var q = HttpUtility.UrlEncode(Model.Street + "," + Model.City + "," + Model.ZipCode);
    var mapurl = $"{mapurlBase}?key={key}&q={q}&maptype=satellite";


    var imagePath = "";
    imagePath = @"~/images/" + Model.id.ToString() + "Appartment.jpg";

}




<div class="Appartment-Details">
    <iframe @*width="600"
                height="450"
                *@="0" style="border:0"
            src="@mapurl" allowfullscreen
            class="Map-iframe"></iframe>
    <div id="right">
        @*<h4>Appartment</h4>
            <hr />*@

        @Html.Action("Details", "Photos", new { id = Model.PhotoID, cssClass = "Appartment-Photo" })
    </div>
    <div id="left">
        <dl class="dl-horizontal">
            <dt>
                Rent Cost
            </dt>

            <dd>
                $@Html.DisplayFor(model => model.RentCost)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Street)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Street)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Country)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Country)
            </dd>
            <dd>

            </dd>
            <dt class="Book-Appointment-Button">
                <button onclick="bookAppointment()" class="Book-Appointment-Button">
                    Book Appointment
                </button>
            </dt>
        </dl>
        @using (Html.BeginForm("BookAppointment", "Appartments", new { id = Model.id }, FormMethod.Post, new { id = "bookAppointment" })) { }
    </div>
    <br style="clear:both;" />
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

@section scripts{
    <script type="text/javascript">

        function bookAppointment() {
            alert("Emailed realitor!");
            //$("#bookAppointment").submit();
        }

        
    </script>
}

Roomie/Views/Appartments/Edit.cshtml
@model Roomie.Models.Appartment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Appartments",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Appartment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.RentCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RentCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RentCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Action("Details", "Photos", new { id = Model.PhotoID, cssClass = "Appartment-Photo" })
           
            <div class="col-md-10">
                <input type="file" id="photoInput" name="photoInput" placeholder="Upload File" />


                @*@Html.DropDownList("PhotoID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.PhotoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Roomie/Views/Appartments/Index.cshtml
@model IEnumerable<Roomie.Models.Appartment>

@{
    ViewBag.Title = "Apartments";
}

<div class="User-Index-Header"><h2>Apartments</h2></div>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            Rent Cost
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            $@Html.DisplayFor(modelItem => item.RentCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Street)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem=>item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.ID }) |*@
            @Html.ActionLink("Details", "Details", new { id=item.id })
            @*@Html.ActionLink("Delete", "Delete", new { id=item.ID })*@
        </td>
    </tr>
}

</table>

Roomie/Views/Appartments/MyAppartments.cshtml
@model Roomie.Models.Appartment

@{
    ViewBag.Title = "MyAppartments";
}

<h2>MyAppartments</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Appartment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RentCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RentCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RentCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Action("Details", "Photos", new { id = Model.PhotoID, cssClass = "Appartment-Photo" })
            @Html.LabelFor(model => model.PhotoID, "PhotoID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="photoInput" name="photoInput" placeholder="Upload File" />


                @*@Html.DropDownList("PhotoID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.PhotoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}